[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fuckme"
version = "1.0.0"
description = "A task reminder that wakes you up with 'fuck' when you're procrastinating"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "playsound>=1.3.0"
]

[project.scripts]
fuckme = "fuckme.cli:main"

[project.urls]
Homepage = "https://github.com/yourusername/fuckme"
Repository = "https://github.com/yourusername/fuckme"
Issues = "https://github.com/yourusername/fuckme/issues"